language: ruby
cache:
  directories:
    - bundle

rvm:
  - 2.4.0
  - 2.3.3
  - 2.1.9
  - 2.0

bundler_args: "--without documentation --path bundle"

before_install:
  - gem install bundler

script:
  - bundle exec danger
